---
run:
  go: "1.17"
  tests: false
  modules-download-mode: vendor
  timeout: 5m

issues:
  exclude-rules:
    - path: vendor

linters:
  enable:
    - gosec
    - gocyclo
    - goconst
    - goimports
    - gocritic
    - govet
    - unconvert
    - revive
    - dupl
    - stylecheck
    - misspell
    - bodyclose
    - contextcheck
    - errcheck
    - gosimple
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - varcheck
    - cyclop

linters-settings:
  errcheck:
    check-blank: true
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
