---
name: Codespell

on:
  pull_request:
  push:

permissions:
  contents: read  #  to fetch code (actions/checkout)

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          ignore_words_file: .github/codespell_ignore_words.txt
          skip: "./vendor"
