name: Go

on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ "1.18", "1.19", "1.20" ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: [ "1.18", "1.19", "1.20" ]

    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v3
      - name: Build
        run: go build -v ./...
      - name: BDD integration test
        run: go test --godog.format=pretty --godog.tags=@~exception general
        working-directory: internal/test/bdd/integration_tests
