---
name: Lint Code Base
on:
  push:
jobs:
  # Lint project
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_GO: true
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE: .*vendor/.*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
